/* SQLite is deliberate for the pilot (one container, one file to back up — same as rally).
   Every query lives here; moving to Postgres later means porting this module, nothing else. */
import Database from "better-sqlite3";
import { mkdirSync } from "node:fs";
import { dirname } from "node:path";

const path = process.env.DATABASE_PATH || "data/cloud.db";
mkdirSync(dirname(path), { recursive: true });
export const DATA_DIR = dirname(path);
export const db = new Database(path);
db.pragma("journal_mode = WAL");
db.pragma("foreign_keys = ON");

db.exec(`
CREATE TABLE IF NOT EXISTS org (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  created REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY,
  org_id INTEGER NOT NULL REFERENCES org(id),
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL DEFAULT '',
  pass_hash TEXT NOT NULL,
  created REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS session (
  token TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES user(id),
  created REAL NOT NULL,
  expires REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS device (
  id TEXT PRIMARY KEY,              -- generated by the device on first boot
  org_id INTEGER REFERENCES org(id),-- NULL until claimed
  kind TEXT NOT NULL,               -- dock | go
  name TEXT NOT NULL DEFAULT '',    -- display name in the console
  secret_hash TEXT NOT NULL,        -- sha256 of the device's secret (trust on first connect)
  claim_code TEXT NOT NULL,
  version TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT '{}',-- latest status payload (metadata only, never job content)
  created REAL NOT NULL,
  claimed_at REAL,
  last_seen REAL
);
CREATE TABLE IF NOT EXISTS event (
  id INTEGER PRIMARY KEY,
  device_id TEXT NOT NULL REFERENCES device(id) ON DELETE CASCADE,
  at REAL NOT NULL,
  type TEXT NOT NULL,
  data TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS event_device ON event(device_id, at);
CREATE TABLE IF NOT EXISTS reset (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES user(id),
  token_hash TEXT NOT NULL UNIQUE,
  created REAL NOT NULL,
  expires REAL NOT NULL,
  used_at REAL
);
CREATE TABLE IF NOT EXISTS invite (
  id INTEGER PRIMARY KEY,
  org_id INTEGER NOT NULL REFERENCES org(id),
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'member',
  token_hash TEXT NOT NULL UNIQUE,   -- sha256 of the one-time token; the raw token exists only in the sent link
  invited_by INTEGER NOT NULL REFERENCES user(id),
  created REAL NOT NULL,
  expires REAL NOT NULL,
  used_at REAL
);
`);

// users grew a role; the first user of each existing org becomes its admin
if (!(db.prepare("PRAGMA table_info(user)").all() as { name: string }[]).some((c) => c.name === "role")) {
  db.exec("ALTER TABLE user ADD COLUMN role TEXT NOT NULL DEFAULT 'member'");
  db.exec("UPDATE user SET role='admin' WHERE id IN (SELECT MIN(id) FROM user GROUP BY org_id)");
}
// self-registration creates a personal org at join time (invite rows carry a flag;
// their org_id/invited_by are placeholders to satisfy the FKs)
if (!(db.prepare("PRAGMA table_info(invite)").all() as { name: string }[]).some((c) => c.name === "personal"))
  db.exec("ALTER TABLE invite ADD COLUMN personal INTEGER NOT NULL DEFAULT 0");

// account features: avatar + TOTP 2FA
{
  const cols = (db.prepare("PRAGMA table_info(user)").all() as { name: string }[]).map((c) => c.name);
  if (!cols.includes("avatar")) db.exec("ALTER TABLE user ADD COLUMN avatar TEXT");
  if (!cols.includes("totp_secret")) db.exec("ALTER TABLE user ADD COLUMN totp_secret TEXT");
  if (!cols.includes("totp_pending")) db.exec("ALTER TABLE user ADD COLUMN totp_pending TEXT");
}
// API keys became personal (they act as their owner, read-only)
{
  const kcols = (db.prepare("PRAGMA table_info(api_key)").all() as { name: string }[]).map((c) => c.name);
  if (kcols.length && !kcols.includes("user_id")) {
    db.exec("ALTER TABLE api_key ADD COLUMN user_id INTEGER REFERENCES user(id)");
    db.exec("UPDATE api_key SET user_id = (SELECT MIN(id) FROM user WHERE user.org_id = api_key.org_id) WHERE user_id IS NULL");
  }
}

// company/billing profile on the org (what invoices will need)
{
  const ocols = (db.prepare("PRAGMA table_info(org)").all() as { name: string }[]).map((c) => c.name);
  for (const col of ["company_name", "contact_name", "billing_email", "phone", "address", "zip", "city", "country", "vat_id", "logo"])
    if (!ocols.includes(col)) db.exec(`ALTER TABLE org ADD COLUMN ${col} TEXT`);
}

// fleet features: sites, diagnostics, per-day usage, API keys
{
  const dcols = (db.prepare("PRAGMA table_info(device)").all() as { name: string }[]).map((c) => c.name);
  if (!dcols.includes("site")) db.exec("ALTER TABLE device ADD COLUMN site TEXT");
  if (!dcols.includes("target_version")) db.exec("ALTER TABLE device ADD COLUMN target_version TEXT");
if (!dcols.includes("approved")) db.exec("ALTER TABLE device ADD COLUMN approved INTEGER NOT NULL DEFAULT 1");
if (!dcols.includes("claimed_by")) db.exec("ALTER TABLE device ADD COLUMN claimed_by INTEGER");
  if (!dcols.includes("diag")) db.exec("ALTER TABLE device ADD COLUMN diag TEXT");
  if (!dcols.includes("mirror_to")) db.exec("ALTER TABLE device ADD COLUMN mirror_to TEXT");   // v1, unused now
  if (!dcols.includes("mirror_from")) db.exec("ALTER TABLE device ADD COLUMN mirror_from TEXT"); // Print2Go: the Dock a Go device pulls from
  // Print2Go shared-pool job: claimable by the source Dock + every phone mirroring it
  const mjCols = (db.prepare("PRAGMA table_info(mirror_job)").all() as { name: string }[]).map((c) => c.name);
  if (mjCols.length && !mjCols.includes("dock_id")) db.exec("DROP TABLE mirror_job");   // v1 schema → rebuild (jobs are ephemeral)
  db.exec(`CREATE TABLE IF NOT EXISTS mirror_job(
    id TEXT PRIMARY KEY,
    dock_id TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    path TEXT NOT NULL,
    created INTEGER NOT NULL,
    claimed_by TEXT,
    claimed_at INTEGER
  )`);
  if (!dcols.includes("diag_at")) db.exec("ALTER TABLE device ADD COLUMN diag_at REAL");
  if (!dcols.includes("dormant")) db.exec("ALTER TABLE device ADD COLUMN dormant INTEGER NOT NULL DEFAULT 0"); // signed out but still a seat
  if (!dcols.includes("platform")) db.exec("ALTER TABLE device ADD COLUMN platform TEXT"); // ios | android for Go apps
  if (!dcols.includes("push_token")) db.exec("ALTER TABLE device ADD COLUMN push_token TEXT"); // APNs device token
  if (!dcols.includes("push_env")) db.exec("ALTER TABLE device ADD COLUMN push_env TEXT");     // sandbox | production
}
db.exec(`
CREATE TABLE IF NOT EXISTS device_stat (
  device_id TEXT NOT NULL REFERENCES device(id) ON DELETE CASCADE,
  day TEXT NOT NULL,                -- YYYY-MM-DD, device-local enough for a sparkline
  jobs INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (device_id, day)
);
CREATE TABLE IF NOT EXISTS release (
  id INTEGER PRIMARY KEY,
  version TEXT NOT NULL UNIQUE,
  channel TEXT NOT NULL DEFAULT 'stable',
  notes TEXT NOT NULL DEFAULT '',
  sha256 TEXT NOT NULL,
  size INTEGER NOT NULL,
  created REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS org_event (
  id INTEGER PRIMARY KEY,
  org_id INTEGER NOT NULL REFERENCES org(id),
  at REAL NOT NULL,
  type TEXT NOT NULL,
  actor TEXT NOT NULL DEFAULT '',
  data TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS org_event_org ON org_event(org_id, at);
CREATE TABLE IF NOT EXISTS api_key (
  id INTEGER PRIMARY KEY,
  org_id INTEGER NOT NULL REFERENCES org(id),
  name TEXT NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,
  created REAL NOT NULL,
  last_used REAL
);
`);

db.exec(`
CREATE TABLE IF NOT EXISTS twofa_login (
  token TEXT PRIMARY KEY,           -- password already verified; waiting for the code
  user_id INTEGER NOT NULL REFERENCES user(id),
  attempts INTEGER NOT NULL DEFAULT 0,
  expires REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS recovery_code (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES user(id),
  code_hash TEXT NOT NULL,
  used_at REAL
);
CREATE TABLE IF NOT EXISTS dock_sheet (
  dock_id TEXT NOT NULL,
  sheet_id TEXT NOT NULL,
  name TEXT NOT NULL DEFAULT '',
  address TEXT NOT NULL DEFAULT '',
  link TEXT NOT NULL DEFAULT '',
  model TEXT NOT NULL DEFAULT '{}',
  tag_uid TEXT,
  tag_programmed INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (dock_id, sheet_id)
);
`);

const now = () => Date.now() / 1000;

export type OrgRow = {
  id: number; name: string; created: number;
  company_name: string | null; contact_name: string | null; billing_email: string | null; phone: string | null;
  address: string | null; zip: string | null; city: string | null; country: string | null; vat_id: string | null;
  logo: string | null;
};
export const setOrgLogo = (id: number, logo: string | null) => db.prepare("UPDATE org SET logo=? WHERE id=?").run(logo, id);
export const COMPANY_FIELDS = ["company_name", "contact_name", "billing_email", "phone", "address", "zip", "city", "country", "vat_id"] as const;
export const updateCompany = (orgId: number, values: Record<string, string | null>) => {
  const cols = COMPANY_FIELDS.filter((f) => f in values);
  if (!cols.length) return;
  db.prepare(`UPDATE org SET ${cols.map((c) => `${c}=?`).join(", ")} WHERE id=?`).run(...cols.map((c) => values[c]), orgId);
};
export type UserRow = {
  id: number; org_id: number; email: string; name: string; pass_hash: string; created: number; role: string;
  avatar: string | null; totp_secret: string | null; totp_pending: string | null;
};
export type InviteRow = { id: number; org_id: number; email: string; role: string; token_hash: string; invited_by: number; created: number; expires: number; used_at: number | null; personal: number };
export type DeviceRow = {
  id: string; org_id: number | null; kind: string; name: string; secret_hash: string;
  claim_code: string; version: string; status: string; created: number; claimed_at: number | null; last_seen: number | null;
  site: string | null; diag: string | null; diag_at: number | null; target_version: string | null;
  approved: number; claimed_by: number | null; mirror_to: string | null; mirror_from: string | null; dormant: number;
  platform: string | null; push_token: string | null; push_env: string | null;
};
export type MirrorJobRow = { id: string; dock_id: string; name: string; type: string; path: string; created: number; claimed_by: string | null; claimed_at: number | null };

// ── orgs & users ────────────────────────────────────────────────────────────
export const getOrg = (id: number) => db.prepare("SELECT * FROM org WHERE id=?").get(id) as OrgRow | undefined;
export const getOrgByName = (name: string) => db.prepare("SELECT * FROM org WHERE name=?").get(name) as OrgRow | undefined;
export const createOrg = (name: string): OrgRow => {
  const r = db.prepare("INSERT INTO org(name, created) VALUES(?,?)").run(name, now());
  return getOrg(Number(r.lastInsertRowid))!;
};
export const getUserByEmail = (email: string) => db.prepare("SELECT * FROM user WHERE email=?").get(email.toLowerCase()) as UserRow | undefined;
export const getUser = (id: number) => db.prepare("SELECT * FROM user WHERE id=?").get(id) as UserRow | undefined;
export const createUser = (orgId: number, email: string, name: string, passHash: string, role = "member") =>
  db.prepare("INSERT INTO user(org_id, email, name, pass_hash, created, role) VALUES(?,?,?,?,?,?)").run(orgId, email.toLowerCase(), name, passHash, now(), role);
export const firstAdmin = (orgId: number) =>
  db.prepare("SELECT * FROM user WHERE org_id=? AND role='admin' ORDER BY id LIMIT 1").get(orgId) as UserRow | undefined;
export const orgUsers = (orgId: number) =>
  db.prepare("SELECT id, email, name, role, created, avatar FROM user WHERE org_id=? ORDER BY created").all(orgId) as Pick<UserRow, "id" | "email" | "name" | "role" | "created" | "avatar">[];
export const setUserName = (id: number, name: string) => db.prepare("UPDATE user SET name=? WHERE id=?").run(name, id);
export const setUserAvatar = (id: number, avatar: string | null) => db.prepare("UPDATE user SET avatar=? WHERE id=?").run(avatar, id);
export const deleteOtherSessions = (userId: number, keep: string) => db.prepare("DELETE FROM session WHERE user_id=? AND token<>?").run(userId, keep);

// ── 2FA ─────────────────────────────────────────────────────────────────────
export const setTotpPending = (id: number, secret: string) => db.prepare("UPDATE user SET totp_pending=? WHERE id=?").run(secret, id);
export const enableTotp = (id: number, secret: string) => db.prepare("UPDATE user SET totp_secret=?, totp_pending=NULL WHERE id=?").run(secret, id);
export const disableTotp = (id: number) => {
  db.prepare("DELETE FROM recovery_code WHERE user_id=?").run(id);
  return db.prepare("UPDATE user SET totp_secret=NULL, totp_pending=NULL WHERE id=?").run(id);
};
export const addRecoveryCodes = (userId: number, hashes: string[]) => {
  db.prepare("DELETE FROM recovery_code WHERE user_id=?").run(userId);
  const ins = db.prepare("INSERT INTO recovery_code(user_id, code_hash) VALUES(?,?)");
  for (const h of hashes) ins.run(userId, h);
};
export const useRecoveryCode = (userId: number, hash: string): boolean =>
  db.prepare("UPDATE recovery_code SET used_at=? WHERE user_id=? AND code_hash=? AND used_at IS NULL").run(now(), userId, hash).changes > 0;
export const createLoginPending = (token: string, userId: number) =>
  db.prepare("INSERT INTO twofa_login(token, user_id, expires) VALUES(?,?,?)").run(token, userId, now() + 300);
export const loginPendingByToken = (token: string) => {
  const r = db.prepare("SELECT * FROM twofa_login WHERE token=?").get(token) as { token: string; user_id: number; attempts: number; expires: number } | undefined;
  return r && r.expires > now() ? r : undefined;
};
export const bumpLoginPending = (token: string) => db.prepare("UPDATE twofa_login SET attempts=attempts+1 WHERE token=?").run(token);
export const deleteLoginPending = (token: string) => db.prepare("DELETE FROM twofa_login WHERE token=?").run(token);
export const deleteUser = (id: number) => {
  db.prepare("DELETE FROM session WHERE user_id=?").run(id);
  db.prepare("DELETE FROM invite WHERE invited_by=? AND used_at IS NULL").run(id);
  return db.prepare("DELETE FROM user WHERE id=?").run(id);
};

// ── password resets ─────────────────────────────────────────────────────────
export type ResetRow = { id: number; user_id: number; token_hash: string; created: number; expires: number; used_at: number | null };
export const createReset = (userId: number, tokenHash: string, hours = 2) =>
  db.prepare("INSERT INTO reset(user_id, token_hash, created, expires) VALUES(?,?,?,?)").run(userId, tokenHash, now(), now() + hours * 3600);
export const resetByTokenHash = (tokenHash: string) => {
  const r = db.prepare("SELECT * FROM reset WHERE token_hash=?").get(tokenHash) as ResetRow | undefined;
  return r && !r.used_at && r.expires > now() ? r : undefined;
};
export const recentResetFor = (userId: number, minutes = 10) =>
  db.prepare("SELECT id FROM reset WHERE user_id=? AND used_at IS NULL AND created>?").get(userId, now() - minutes * 60) as { id: number } | undefined;
export const markResetUsed = (id: number) => db.prepare("UPDATE reset SET used_at=? WHERE id=?").run(now(), id);
export const updatePassword = (userId: number, passHash: string) => db.prepare("UPDATE user SET pass_hash=? WHERE id=?").run(passHash, userId);
export const deleteSessionsFor = (userId: number) => db.prepare("DELETE FROM session WHERE user_id=?").run(userId);

// ── invites ─────────────────────────────────────────────────────────────────
export const createInvite = (orgId: number, email: string, role: string, tokenHash: string, invitedBy: number, days = 14, personal = false) =>
  db.prepare("INSERT INTO invite(org_id, email, role, token_hash, invited_by, created, expires, personal) VALUES(?,?,?,?,?,?,?,?)")
    .run(orgId, email.toLowerCase(), role, tokenHash, invitedBy, now(), now() + days * 86400, personal ? 1 : 0);
export const renameOrg = (id: number, name: string) => db.prepare("UPDATE org SET name=? WHERE id=?").run(name, id);
export const anyOrgAdmin = () =>
  db.prepare("SELECT * FROM user WHERE role='admin' ORDER BY org_id, id LIMIT 1").get() as UserRow | undefined;
export const inviteByTokenHash = (tokenHash: string) => {
  const i = db.prepare("SELECT * FROM invite WHERE token_hash=?").get(tokenHash) as InviteRow | undefined;
  return i && !i.used_at && i.expires > now() ? i : undefined;
};
export const pendingInviteFor = (orgId: number, email: string) =>
  db.prepare("SELECT * FROM invite WHERE org_id=? AND email=? AND used_at IS NULL AND expires>?").get(orgId, email.toLowerCase(), now()) as InviteRow | undefined;
export const orgInvites = (orgId: number) =>
  db.prepare(`SELECT i.id, i.email, i.role, i.created, i.expires, u.email AS invited_by_email
              FROM invite i JOIN user u ON u.id = i.invited_by
              WHERE i.org_id=? AND i.used_at IS NULL AND i.expires>? ORDER BY i.created`).all(orgId, now()) as
    { id: number; email: string; role: string; created: number; expires: number; invited_by_email: string }[];
export const markInviteUsed = (id: number) => db.prepare("UPDATE invite SET used_at=? WHERE id=?").run(now(), id);
export const revokeInvite = (id: number, orgId: number) => db.prepare("DELETE FROM invite WHERE id=? AND org_id=? AND used_at IS NULL").run(id, orgId);

// ── sessions ────────────────────────────────────────────────────────────────
export const createSession = (token: string, userId: number, days = 30) =>
  db.prepare("INSERT INTO session(token, user_id, created, expires) VALUES(?,?,?,?)").run(token, userId, now(), now() + days * 86400);
export const getSession = (token: string) => {
  const s = db.prepare("SELECT * FROM session WHERE token=?").get(token) as { token: string; user_id: number; expires: number } | undefined;
  if (!s || s.expires < now()) return undefined;
  return s;
};
export const deleteSession = (token: string) => db.prepare("DELETE FROM session WHERE token=?").run(token);

// ── devices ─────────────────────────────────────────────────────────────────
export const getDevice = (id: string) => db.prepare("SELECT * FROM device WHERE id=?").get(id) as DeviceRow | undefined;
export const registerDevice = (id: string, kind: string, name: string, secretHash: string, claimCode: string, version: string) =>
  db.prepare("INSERT INTO device(id, org_id, kind, name, secret_hash, claim_code, version, created, last_seen) VALUES(?,NULL,?,?,?,?,?,?,?)")
    .run(id, kind, name, secretHash, claimCode, version, now(), now());
export const touchDevice = (id: string, version?: string) =>
  version === undefined
    ? db.prepare("UPDATE device SET last_seen=? WHERE id=?").run(now(), id)
    : db.prepare("UPDATE device SET last_seen=?, version=? WHERE id=?").run(now(), version, id);
export const saveDeviceStatus = (id: string, status: string) =>
  db.prepare("UPDATE device SET status=?, last_seen=? WHERE id=?").run(status, now(), id);
/** Which mobile platform a Go app runs on (ios | android) — for the Updates page tabs. */
export const setDevicePlatform = (id: string, platform: string) =>
  db.prepare("UPDATE device SET platform=? WHERE id=? AND (platform IS NULL OR platform!=?)").run(platform, id, platform);
/** The APNs token a Go app reports, so the cloud can wake it for a waiting job. */
export const setPushToken = (id: string, token: string, env: string) =>
  db.prepare("UPDATE device SET push_token=?, push_env=? WHERE id=?").run(token, env, id);
export const clearPushToken = (id: string) =>
  db.prepare("UPDATE device SET push_token=NULL WHERE id=?").run(id);

// ── Print2Go: a Dock's sheets, inherited by its paired phones as Dock-Labels ──
export type DockSheetRow = {
  dock_id: string; sheet_id: string; name: string; address: string;
  link: string; model: string; tag_uid: string | null; tag_programmed: number;
};
export const dockSheets = (dockId: string): DockSheetRow[] =>
  db.prepare("SELECT * FROM dock_sheet WHERE dock_id=? ORDER BY sheet_id").all(dockId) as DockSheetRow[];

type IncomingSheet = { id: string; name?: string; address?: string; link?: string; model?: string; tag_uid?: string | null; tag_programmed?: boolean };
/** Snapshot upsert: the Dock owns the definition zone. Rows it no longer lists are
 *  dropped; a snapshot that omits NFC leaves a phone-learned tag intact. */
export const syncDockSheets = (dockId: string, sheets: IncomingSheet[]): void => {
  const keep = new Set(sheets.map((s) => s.id));
  const existing = new Map(dockSheets(dockId).map((r) => [r.sheet_id, r]));
  const del = db.prepare("DELETE FROM dock_sheet WHERE dock_id=? AND sheet_id=?");
  for (const id of existing.keys()) if (!keep.has(id)) del.run(dockId, id);
  const up = db.prepare(`INSERT INTO dock_sheet(dock_id,sheet_id,name,address,link,model,tag_uid,tag_programmed)
    VALUES(@dock_id,@sheet_id,@name,@address,@link,@model,@tag_uid,@tag_programmed)
    ON CONFLICT(dock_id,sheet_id) DO UPDATE SET name=@name,address=@address,link=@link,model=@model,
      tag_uid=COALESCE(@tag_uid,tag_uid), tag_programmed=CASE WHEN @tag_uid IS NULL THEN tag_programmed ELSE @tag_programmed END`);
  for (const s of sheets) {
    const prev = existing.get(s.id);
    up.run({
      dock_id: dockId, sheet_id: s.id, name: s.name ?? "", address: s.address ?? "",
      link: s.link ?? "", model: s.model ?? "{}",
      tag_uid: s.tag_uid ?? null,
      tag_programmed: s.tag_programmed ? 1 : (prev?.tag_programmed ?? 0),
    });
  }
};
/** The one bidirectional field — any device may set it; returns the updated row. */
export const setDockSheetNfc = (dockId: string, sheetId: string, uid: string | null, programmed: boolean): DockSheetRow | undefined => {
  db.prepare("UPDATE dock_sheet SET tag_uid=?, tag_programmed=? WHERE dock_id=? AND sheet_id=?")
    .run(uid, programmed ? 1 : 0, dockId, sheetId);
  return db.prepare("SELECT * FROM dock_sheet WHERE dock_id=? AND sheet_id=?").get(dockId, sheetId) as DockSheetRow | undefined;
};

// ── Print2Go: a Dock's jobs print on the phones mirroring it (shared pool) ─────
/** A Go device pulls jobs from this Dock (or null to stop). */
export const setMirrorFrom = (id: string, dockId: string | null) =>
  db.prepare("UPDATE device SET mirror_from=? WHERE id=?").run(dockId, id);
/** Every phone currently mirroring a given Dock. */
export const mirrorPhones = (dockId: string) =>
  db.prepare("SELECT * FROM device WHERE mirror_from=?").all(dockId) as DeviceRow[];
/** Does a device offer Print2Go? A Dock Light always does; a full Dock via its status flag. */
export const isPrint2Go = (d: DeviceRow): boolean => {
  if (d.kind === "dock-light") return true;
  try { return JSON.parse(d.status).print2go === true; } catch { return false; }
};
/** The org's Docks that offer Print2Go — what a phone can choose to mirror. */
export const print2goDocks = (orgId: number) =>
  (db.prepare("SELECT * FROM device WHERE org_id=? AND kind IN ('dock','dock-light')").all(orgId) as DeviceRow[])
    .filter(isPrint2Go);

export const addMirrorJob = (j: MirrorJobRow) =>
  db.prepare("INSERT INTO mirror_job(id, dock_id, name, type, path, created, claimed_by, claimed_at) VALUES(?,?,?,?,?,?,?,?)")
    .run(j.id, j.dock_id, j.name, j.type, j.path, j.created, j.claimed_by, j.claimed_at);
export const getMirrorJob = (id: string) => db.prepare("SELECT * FROM mirror_job WHERE id=?").get(id) as MirrorJobRow | undefined;
export const deleteMirrorJob = (id: string) => db.prepare("DELETE FROM mirror_job WHERE id=?").run(id);
/** Atomic claim: only the first caller wins (returns true). */
export const claimMirrorJob = (id: string, by: string): boolean =>
  db.prepare("UPDATE mirror_job SET claimed_by=?, claimed_at=? WHERE id=? AND claimed_by IS NULL").run(by, now(), id).changes > 0;
/** Re-open a job the claimer couldn't finish. */
export const releaseMirrorJob = (id: string) =>
  db.prepare("UPDATE mirror_job SET claimed_by=NULL, claimed_at=NULL WHERE id=?").run(id);
/** Unclaimed jobs waiting for a given recipient (the source Dock, or a phone mirroring it). */
export const openMirrorJobsFor = (deviceId: string): MirrorJobRow[] => {
  const d = getDevice(deviceId);
  if (!d) return [];
  const dockId = d.kind === "go" ? d.mirror_from : d.id;   // a phone waits on its source Dock; a Dock on itself
  if (!dockId) return [];
  return db.prepare("SELECT * FROM mirror_job WHERE dock_id=? AND claimed_by IS NULL ORDER BY created").all(dockId) as MirrorJobRow[];
};
export const staleMirrorJobs = (olderThan: number) =>
  db.prepare("SELECT * FROM mirror_job WHERE created < ?").all(olderThan) as MirrorJobRow[];
/** The name a device goes by: its status payload's printer name, else the hello name, else the id. */
export const deviceLabel = (d: DeviceRow): string => {
  try { const p = JSON.parse(d.status).printer; if (typeof p === "string" && p) return p; } catch {}
  return d.name || d.id.slice(0, 8);
};
export const renameDevice = (id: string, name: string) => db.prepare("UPDATE device SET name=? WHERE id=?").run(name, id);
/** A device can change its kind (a Dock reconfigured as a Dock Light, say) — honor it on reconnect. */
export const setDeviceKind = (id: string, kind: string) => db.prepare("UPDATE device SET kind=? WHERE id=?").run(kind, id);
export const setTargetVersion = (id: string, v: string | null) => db.prepare("UPDATE device SET target_version=? WHERE id=?").run(v, id);
export const setDeviceSite = (id: string, site: string | null) => db.prepare("UPDATE device SET site=? WHERE id=?").run(site, id);
export const saveDiag = (id: string, diag: string) => db.prepare("UPDATE device SET diag=?, diag_at=? WHERE id=?").run(diag, now(), id);
export const upsertStat = (deviceId: string, day: string, jobs: number) =>
  db.prepare("INSERT INTO device_stat(device_id, day, jobs) VALUES(?,?,?) ON CONFLICT(device_id, day) DO UPDATE SET jobs=excluded.jobs").run(deviceId, day, jobs);
export const deviceStats = (deviceId: string, days = 14) =>
  db.prepare("SELECT day, jobs FROM device_stat WHERE device_id=? ORDER BY day DESC LIMIT ?").all(deviceId, days) as { day: string; jobs: number }[];
export const orgPagesTotal = (orgId: number): number =>
  (db.prepare("SELECT COALESCE(SUM(s.jobs),0) AS n FROM device_stat s JOIN device d ON d.id=s.device_id WHERE d.org_id=?")
    .get(orgId) as { n: number }).n;
export const orgActivity = (orgId: number, limit = 60) =>
  db.prepare(`SELECT e.at, e.type, e.data, d.id AS device_id, d.name AS device_name, d.kind
              FROM event e JOIN device d ON d.id = e.device_id
              WHERE d.org_id=? ORDER BY e.at DESC LIMIT ?`).all(orgId, limit) as
    { at: number; type: string; data: string; device_id: string; device_name: string; kind: string }[];
export const setUserRole = (id: number, role: string) => db.prepare("UPDATE user SET role=? WHERE id=?").run(role, id);
export const addOrgEvent = (orgId: number, type: string, actor = "", data = "") =>
  db.prepare("INSERT INTO org_event(org_id, at, type, actor, data) VALUES(?,?,?,?,?)").run(orgId, now(), type, actor, data);
export const orgEvents = (orgId: number, limit = 60) =>
  db.prepare("SELECT at, type, actor, data FROM org_event WHERE org_id=? ORDER BY at DESC LIMIT ?").all(orgId, limit) as
    { at: number; type: string; actor: string; data: string }[];

// ── API keys ────────────────────────────────────────────────────────────────
export type ApiKeyRow = { id: number; org_id: number; user_id: number | null; name: string; token_hash: string; created: number; last_used: number | null };
export const createApiKey = (orgId: number, userId: number, name: string, tokenHash: string) =>
  db.prepare("INSERT INTO api_key(org_id, user_id, name, token_hash, created) VALUES(?,?,?,?,?)").run(orgId, userId, name, tokenHash, now());
export const userApiKeys = (userId: number) =>
  db.prepare("SELECT id, name, created, last_used FROM api_key WHERE user_id=? ORDER BY created").all(userId) as Omit<ApiKeyRow, "org_id" | "user_id" | "token_hash">[];
export const apiKeyByHash = (hash: string) => {
  const k = db.prepare("SELECT * FROM api_key WHERE token_hash=?").get(hash) as ApiKeyRow | undefined;
  if (k) db.prepare("UPDATE api_key SET last_used=? WHERE id=?").run(now(), k.id);
  return k;
};
export const revokeApiKey = (id: number, userId: number) => db.prepare("DELETE FROM api_key WHERE id=? AND user_id=?").run(id, userId);

// ── software releases (vendor-level: the RePaper software itself) ──────────
export type ReleaseRow = { id: number; version: string; channel: string; notes: string; sha256: string; size: number; created: number };
export const createRelease = (version: string, channel: string, notes: string, sha256: string, size: number) =>
  db.prepare("INSERT INTO release(version, channel, notes, sha256, size, created) VALUES(?,?,?,?,?,?)").run(version, channel, notes, sha256, size, now());
export const listReleases = () => db.prepare("SELECT * FROM release ORDER BY created DESC LIMIT 20").all() as ReleaseRow[];
export const getRelease = (version: string) => db.prepare("SELECT * FROM release WHERE version=?").get(version) as ReleaseRow | undefined;
export const latestRelease = (channel = "stable") =>
  db.prepare("SELECT * FROM release WHERE channel=? ORDER BY created DESC LIMIT 1").get(channel) as ReleaseRow | undefined;

// ── public aggregate (status page) ──────────────────────────────────────────
export const publicCounts = () =>
  db.prepare("SELECT COUNT(*) AS devices, COUNT(DISTINCT org_id) AS orgs FROM device WHERE org_id IS NOT NULL").get() as { devices: number; orgs: number };
export const orgDevices = (orgId: number) => db.prepare("SELECT * FROM device WHERE org_id=? ORDER BY created").all(orgId) as DeviceRow[];
export const findClaimable = (code: string) =>
  db.prepare("SELECT * FROM device WHERE org_id IS NULL AND claim_code=? ORDER BY last_seen DESC").get(code) as DeviceRow | undefined;
/** Any device with this claim code — including an already-claimed or dormant one (for re-sign-in). */
export const findByClaimCode = (code: string) =>
  db.prepare("SELECT * FROM device WHERE claim_code=? ORDER BY last_seen DESC").get(code) as DeviceRow | undefined;
export const claimDevice = (id: string, orgId: number, approved = 1, byUser: number | null = null) =>
  db.prepare("UPDATE device SET org_id=?, claimed_at=?, approved=?, claimed_by=?, dormant=0 WHERE id=?").run(orgId, now(), approved, byUser, id);
/** Sign-out: keep the row (and the seat), just mark it dormant so the app's gate returns. */
export const markDormant = (id: string) => db.prepare("UPDATE device SET dormant=1 WHERE id=?").run(id);
/** Re-sign-in on a dormant device the org already owns — wake it, no new seat. */
export const reactivateDevice = (id: string) => db.prepare("UPDATE device SET dormant=0 WHERE id=?").run(id);
export const approveDevice = (id: string) => db.prepare("UPDATE device SET approved=1 WHERE id=?").run(id);
export const deleteDevice = (id: string) => db.prepare("DELETE FROM device WHERE id=?").run(id);

// ── events ──────────────────────────────────────────────────────────────────
export const addEvent = (deviceId: string, type: string, data = "") =>
  db.prepare("INSERT INTO event(device_id, at, type, data) VALUES(?,?,?,?)").run(deviceId, now(), type, data);
export const deviceEvents = (deviceId: string, limit = 10) =>
  db.prepare("SELECT at, type, data FROM event WHERE device_id=? ORDER BY at DESC LIMIT ?").all(deviceId, limit) as { at: number; type: string; data: string }[];
