/* SQLite is deliberate for the pilot (one container, one file to back up — same as rally).
   Every query lives here; moving to Postgres later means porting this module, nothing else. */
import Database from "better-sqlite3";
import { mkdirSync } from "node:fs";
import { dirname } from "node:path";

const path = process.env.DATABASE_PATH || "data/cloud.db";
mkdirSync(dirname(path), { recursive: true });
export const db = new Database(path);
db.pragma("journal_mode = WAL");
db.pragma("foreign_keys = ON");

db.exec(`
CREATE TABLE IF NOT EXISTS org (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  created REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY,
  org_id INTEGER NOT NULL REFERENCES org(id),
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL DEFAULT '',
  pass_hash TEXT NOT NULL,
  created REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS session (
  token TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES user(id),
  created REAL NOT NULL,
  expires REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS device (
  id TEXT PRIMARY KEY,              -- generated by the device on first boot
  org_id INTEGER REFERENCES org(id),-- NULL until claimed
  kind TEXT NOT NULL,               -- dock | go
  name TEXT NOT NULL DEFAULT '',    -- display name in the console
  secret_hash TEXT NOT NULL,        -- sha256 of the device's secret (trust on first connect)
  claim_code TEXT NOT NULL,
  version TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT '{}',-- latest status payload (metadata only, never job content)
  created REAL NOT NULL,
  claimed_at REAL,
  last_seen REAL
);
CREATE TABLE IF NOT EXISTS event (
  id INTEGER PRIMARY KEY,
  device_id TEXT NOT NULL REFERENCES device(id) ON DELETE CASCADE,
  at REAL NOT NULL,
  type TEXT NOT NULL,
  data TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS event_device ON event(device_id, at);
CREATE TABLE IF NOT EXISTS invite (
  id INTEGER PRIMARY KEY,
  org_id INTEGER NOT NULL REFERENCES org(id),
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'member',
  token_hash TEXT NOT NULL UNIQUE,   -- sha256 of the one-time token; the raw token exists only in the sent link
  invited_by INTEGER NOT NULL REFERENCES user(id),
  created REAL NOT NULL,
  expires REAL NOT NULL,
  used_at REAL
);
`);

// users grew a role; the first user of each existing org becomes its admin
if (!(db.prepare("PRAGMA table_info(user)").all() as { name: string }[]).some((c) => c.name === "role")) {
  db.exec("ALTER TABLE user ADD COLUMN role TEXT NOT NULL DEFAULT 'member'");
  db.exec("UPDATE user SET role='admin' WHERE id IN (SELECT MIN(id) FROM user GROUP BY org_id)");
}

const now = () => Date.now() / 1000;

export type OrgRow = { id: number; name: string; created: number };
export type UserRow = { id: number; org_id: number; email: string; name: string; pass_hash: string; created: number; role: string };
export type InviteRow = { id: number; org_id: number; email: string; role: string; token_hash: string; invited_by: number; created: number; expires: number; used_at: number | null };
export type DeviceRow = {
  id: string; org_id: number | null; kind: string; name: string; secret_hash: string;
  claim_code: string; version: string; status: string; created: number; claimed_at: number | null; last_seen: number | null;
};

// ── orgs & users ────────────────────────────────────────────────────────────
export const getOrg = (id: number) => db.prepare("SELECT * FROM org WHERE id=?").get(id) as OrgRow | undefined;
export const getOrgByName = (name: string) => db.prepare("SELECT * FROM org WHERE name=?").get(name) as OrgRow | undefined;
export const createOrg = (name: string): OrgRow => {
  const r = db.prepare("INSERT INTO org(name, created) VALUES(?,?)").run(name, now());
  return getOrg(Number(r.lastInsertRowid))!;
};
export const getUserByEmail = (email: string) => db.prepare("SELECT * FROM user WHERE email=?").get(email.toLowerCase()) as UserRow | undefined;
export const getUser = (id: number) => db.prepare("SELECT * FROM user WHERE id=?").get(id) as UserRow | undefined;
export const createUser = (orgId: number, email: string, name: string, passHash: string, role = "member") =>
  db.prepare("INSERT INTO user(org_id, email, name, pass_hash, created, role) VALUES(?,?,?,?,?,?)").run(orgId, email.toLowerCase(), name, passHash, now(), role);
export const orgUsers = (orgId: number) =>
  db.prepare("SELECT id, email, name, role, created FROM user WHERE org_id=? ORDER BY created").all(orgId) as Pick<UserRow, "id" | "email" | "name" | "role" | "created">[];
export const deleteUser = (id: number) => {
  db.prepare("DELETE FROM session WHERE user_id=?").run(id);
  db.prepare("DELETE FROM invite WHERE invited_by=? AND used_at IS NULL").run(id);
  return db.prepare("DELETE FROM user WHERE id=?").run(id);
};

// ── invites ─────────────────────────────────────────────────────────────────
export const createInvite = (orgId: number, email: string, role: string, tokenHash: string, invitedBy: number, days = 14) =>
  db.prepare("INSERT INTO invite(org_id, email, role, token_hash, invited_by, created, expires) VALUES(?,?,?,?,?,?,?)")
    .run(orgId, email.toLowerCase(), role, tokenHash, invitedBy, now(), now() + days * 86400);
export const inviteByTokenHash = (tokenHash: string) => {
  const i = db.prepare("SELECT * FROM invite WHERE token_hash=?").get(tokenHash) as InviteRow | undefined;
  return i && !i.used_at && i.expires > now() ? i : undefined;
};
export const pendingInviteFor = (orgId: number, email: string) =>
  db.prepare("SELECT * FROM invite WHERE org_id=? AND email=? AND used_at IS NULL AND expires>?").get(orgId, email.toLowerCase(), now()) as InviteRow | undefined;
export const orgInvites = (orgId: number) =>
  db.prepare(`SELECT i.id, i.email, i.role, i.created, i.expires, u.email AS invited_by_email
              FROM invite i JOIN user u ON u.id = i.invited_by
              WHERE i.org_id=? AND i.used_at IS NULL AND i.expires>? ORDER BY i.created`).all(orgId, now()) as
    { id: number; email: string; role: string; created: number; expires: number; invited_by_email: string }[];
export const markInviteUsed = (id: number) => db.prepare("UPDATE invite SET used_at=? WHERE id=?").run(now(), id);
export const revokeInvite = (id: number, orgId: number) => db.prepare("DELETE FROM invite WHERE id=? AND org_id=? AND used_at IS NULL").run(id, orgId);

// ── sessions ────────────────────────────────────────────────────────────────
export const createSession = (token: string, userId: number, days = 30) =>
  db.prepare("INSERT INTO session(token, user_id, created, expires) VALUES(?,?,?,?)").run(token, userId, now(), now() + days * 86400);
export const getSession = (token: string) => {
  const s = db.prepare("SELECT * FROM session WHERE token=?").get(token) as { token: string; user_id: number; expires: number } | undefined;
  if (!s || s.expires < now()) return undefined;
  return s;
};
export const deleteSession = (token: string) => db.prepare("DELETE FROM session WHERE token=?").run(token);

// ── devices ─────────────────────────────────────────────────────────────────
export const getDevice = (id: string) => db.prepare("SELECT * FROM device WHERE id=?").get(id) as DeviceRow | undefined;
export const registerDevice = (id: string, kind: string, name: string, secretHash: string, claimCode: string, version: string) =>
  db.prepare("INSERT INTO device(id, org_id, kind, name, secret_hash, claim_code, version, created, last_seen) VALUES(?,NULL,?,?,?,?,?,?,?)")
    .run(id, kind, name, secretHash, claimCode, version, now(), now());
export const touchDevice = (id: string, version?: string) =>
  version === undefined
    ? db.prepare("UPDATE device SET last_seen=? WHERE id=?").run(now(), id)
    : db.prepare("UPDATE device SET last_seen=?, version=? WHERE id=?").run(now(), version, id);
export const saveDeviceStatus = (id: string, status: string) =>
  db.prepare("UPDATE device SET status=?, last_seen=? WHERE id=?").run(status, now(), id);
export const renameDevice = (id: string, name: string) => db.prepare("UPDATE device SET name=? WHERE id=?").run(name, id);
export const orgDevices = (orgId: number) => db.prepare("SELECT * FROM device WHERE org_id=? ORDER BY created").all(orgId) as DeviceRow[];
export const findClaimable = (code: string) =>
  db.prepare("SELECT * FROM device WHERE org_id IS NULL AND claim_code=? ORDER BY last_seen DESC").get(code) as DeviceRow | undefined;
export const claimDevice = (id: string, orgId: number) =>
  db.prepare("UPDATE device SET org_id=?, claimed_at=? WHERE id=?").run(orgId, now(), id);
export const deleteDevice = (id: string) => db.prepare("DELETE FROM device WHERE id=?").run(id);

// ── events ──────────────────────────────────────────────────────────────────
export const addEvent = (deviceId: string, type: string, data = "") =>
  db.prepare("INSERT INTO event(device_id, at, type, data) VALUES(?,?,?,?)").run(deviceId, now(), type, data);
export const deviceEvents = (deviceId: string, limit = 10) =>
  db.prepare("SELECT at, type, data FROM event WHERE device_id=? ORDER BY at DESC LIMIT ?").all(deviceId, limit) as { at: number; type: string; data: string }[];
