package net.repaper.go.core

import org.json.JSONObject
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/** Byte-for-byte parity with py-opendisplay (the SDK the Dock uses), via fixtures
 *  generated by go/tools/make_golden.py. */
class GoldenTest {
    private fun golden(name: String): JSONObject =
        JSONObject(javaClass.getResource("/golden/$name.json")!!.readText())

    @Test fun cryptoMatchesSdk() {
        val g = golden("crypto")
        val master = g.getString("master").hexToBytes()
        val cn = g.getString("client_nonce").hexToBytes()
        val sn = g.getString("server_nonce").hexToBytes()
        val devId = g.getString("device_id").hexToBytes()
        val sk = OdCrypto.deriveSessionKey(master, cn, sn, devId)
        assertEquals(g.getString("session_key"), sk.toHexLower())
        assertEquals(g.getString("session_id"), OdCrypto.deriveSessionId(sk, cn, sn).toHexLower())
        assertEquals(g.getString("challenge_response"), OdCrypto.challengeResponse(master, sn, cn, devId).toHexLower())
        assertEquals(g.getString("server_proof"), OdCrypto.serverProof(sk, sn, cn, devId).toHexLower())

        val sid = g.getString("session_id").hexToBytes()
        val frame = OdCrypto.encryptCommand(sk, sid, g.getLong("frame_counter"),
            g.getString("frame_cmd").hexToBytes(), g.getString("frame_payload").hexToBytes())
        assertEquals(g.getString("frame"), frame.toHexLower())

        val (cmd, payload) = OdCrypto.decryptResponse(sk, g.getString("resp_frame").hexToBytes())
        assertEquals(g.getInt("resp_cmd"), cmd)
        assertEquals(g.getString("resp_payload"), payload.toHexLower())
    }

    @Test fun commandFramesMatchSdk() {
        val g = golden("commands")
        val c = golden("crypto")
        assertEquals(g.getString("read_config"), Od.readConfig().toHexLower())
        assertEquals(g.getString("read_fw"), Od.readFwVersion().toHexLower())
        assertEquals(g.getString("auth1"), Od.authStep1().toHexLower())
        val cn = c.getString("client_nonce").hexToBytes()
        val ch = c.getString("challenge_response").hexToBytes()
        assertEquals(g.getString("auth2"), Od.authStep2(cn, ch).toHexLower())
        assertEquals(g.getString("dw_start"), Od.directWriteStartUncompressed().toHexLower())
        assertEquals(g.getString("dw_data"), Od.directWriteData(byteArrayOf(1, 2, 3, 4)).toHexLower())
        assertEquals(g.getString("dw_end_full"), Od.directWriteEnd(0).toHexLower())
        assertEquals(g.getString("dw_end_fast"), Od.directWriteEnd(1).toHexLower())
    }

    @Test fun encodingsMatchSdk() {
        val g = golden("encoding")
        val grid = g.getJSONArray("grid")
        val h = grid.length(); val w = grid.getString(0).length
        // logical letters → RePaper palette indexes (0=white, 1=black, 2=red, 3=yellow)
        val repaper = mapOf('W' to 0, 'B' to 1, 'R' to 2, 'Y' to 3)
        fun indexes(clampAccent: Boolean, yellowAsAccent: Boolean = false): IntArray {
            val out = IntArray(w * h)
            for (y in 0 until h) for (x in 0 until w) {
                var idx = repaper.getValue(grid.getString(y)[x])
                if (yellowAsAccent && idx == 3) idx = 2       // BWR/BWY panels: Y renders as the accent
                if (clampAccent && idx >= 2) idx = 1          // MONO: any accent renders black
                out[y * w + x] = idx
            }
            return out
        }
        assertEquals(g.getString("mono"), OdEncoding.encode(indexes(clampAccent = true), w, h, ColorScheme.MONO).toHexLower())
        assertEquals(g.getString("bwr"), OdEncoding.encode(indexes(false, yellowAsAccent = true), w, h, ColorScheme.BWR).toHexLower())
        assertEquals(g.getString("bwy"), OdEncoding.encode(indexes(false, yellowAsAccent = true), w, h, ColorScheme.BWY).toHexLower())
        assertEquals(g.getString("bwry"), OdEncoding.encode(indexes(false), w, h, ColorScheme.BWRY).toHexLower())
    }

    @Test fun extendedEncodingsMatchSdk() {
        val g = golden("encoding")
        val xg = g.getJSONArray("xgrid")
        val h = xg.length(); val w = xg.getString(0).length
        // letters → OUR palette indexes: BWGBRY/7COLOR palettes are in SDK order (B,W,Y,R,U,G[,O])
        val six = mapOf('B' to 0, 'W' to 1, 'Y' to 2, 'R' to 3, 'U' to 4, 'G' to 5)
        fun idx(seven: Boolean): IntArray = IntArray(w * h) { i ->
            val c = xg.getString(i / w)[i % w]
            if (c == 'O') (if (seven) 6 else 3) else six.getValue(c)
        }
        assertEquals(g.getString("bwgbry"), OdEncoding.encode(idx(false), w, h, ColorScheme.BWGBRY).toHexLower())
        assertEquals(g.getString("bwgbry_split"), OdEncoding.encode(idx(false), w, h, ColorScheme.BWGBRY_SPLIT).toHexLower())
        assertEquals(g.getString("seven"), OdEncoding.encode(idx(true), w, h, ColorScheme.SEVEN_COLOR).toHexLower())

        val gg = g.getJSONArray("graygrid")
        val gidx = IntArray(4 * gg.length()) { i -> gg.getString(i / 4)[i % 4].digitToInt() }
        assertEquals(g.getString("gray4_base"), OdEncoding.encode(gidx, 4, gg.length(), ColorScheme.GRAY4, panelIc = 0x0008).toHexLower())
        assertEquals(g.getString("gray4_v2"), OdEncoding.encode(gidx, 4, gg.length(), ColorScheme.GRAY4, panelIc = 0x0028).toHexLower())

        val g16 = g.getJSONArray("gray16_grid")
        val vals = ArrayList<Int>()
        for (r in 0 until g16.length()) { val row = g16.getJSONArray(r); for (c in 0 until row.length()) vals.add(row.getInt(c)) }
        assertEquals(g.getString("gray16"), OdEncoding.encode(vals.toIntArray(), 4, g16.length(), ColorScheme.GRAY16).toHexLower())

        // per-panel BWRY: 0x001D swaps yellow/red on the wire
        val grid = g.getJSONArray("grid")
        val bh = grid.length(); val bw = grid.getString(0).length
        val rep = mapOf('W' to 0, 'B' to 1, 'R' to 2, 'Y' to 3)
        val bidx = IntArray(bw * bh) { i -> rep.getValue(grid.getString(i / bw)[i % bw]) }
        assertEquals(g.getString("bwry_swapped"), OdEncoding.encode(bidx, bw, bh, ColorScheme.BWRY, panelIc = 0x001D).toHexLower())
    }

    @Test fun schemeEightResolves() {
        assertEquals(ColorScheme.BWGBRY_SPLIT, ColorScheme.fromWire(8))
        assertEquals("BWGBRY", ColorScheme.fromWire(8).paletteKey)
    }

    @Test fun landingUrlsMatchSdk() {
        val g = golden("landing")
        val withKey = g.getJSONObject("with_key")
        val l = LandingUrl.parse(withKey.getString("url"))
        assertEquals(withKey.getInt("tag_type"), l.tagType)
        assertEquals(withKey.getString("device_id"), l.deviceId)
        assertEquals(withKey.getString("name"), l.name)
        assertEquals(withKey.getString("key"), l.keyHex)
        assertEquals(withKey.getInt("manufacturer"), l.manufacturerId)
        val noKey = g.getJSONObject("no_key")
        val l2 = LandingUrl.parse(noKey.getString("url"))
        assertNull(l2.keyHex)
        assertEquals(noKey.getString("name"), l2.name)
    }

    @Test fun configParseMatchesSdk() {
        val g = golden("config")
        val caps = OdConfig.parse(g.getString("tlv").hexToBytes())
        assertEquals(g.getInt("width"), caps.width)
        assertEquals(g.getInt("height"), caps.height)
        assertEquals(g.getString("scheme"), caps.scheme.name)
        assertEquals(g.getInt("rotation_degrees"), caps.rotation)
        assertEquals(g.getInt("panel_ic"), caps.panelIc)
        assertEquals(122, caps.viewedWidth)     // 90° mount: viewed size swaps
        assertEquals(250, caps.viewedHeight)
        assertTrue(caps.sessionTimeoutSeconds == 0)
    }
}
