package net.repaper.go.core

import org.json.JSONObject
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/** Byte-for-byte parity with py-opendisplay (the SDK the Dock uses), via fixtures
 *  generated by go/tools/make_golden.py. */
class GoldenTest {
    private fun golden(name: String): JSONObject =
        JSONObject(javaClass.getResource("/golden/$name.json")!!.readText())

    @Test fun cryptoMatchesSdk() {
        val g = golden("crypto")
        val master = g.getString("master").hexToBytes()
        val cn = g.getString("client_nonce").hexToBytes()
        val sn = g.getString("server_nonce").hexToBytes()
        val devId = g.getString("device_id").hexToBytes()
        val sk = OdCrypto.deriveSessionKey(master, cn, sn, devId)
        assertEquals(g.getString("session_key"), sk.toHexLower())
        assertEquals(g.getString("session_id"), OdCrypto.deriveSessionId(sk, cn, sn).toHexLower())
        assertEquals(g.getString("challenge_response"), OdCrypto.challengeResponse(master, sn, cn, devId).toHexLower())
        assertEquals(g.getString("server_proof"), OdCrypto.serverProof(sk, sn, cn, devId).toHexLower())

        val sid = g.getString("session_id").hexToBytes()
        val frame = OdCrypto.encryptCommand(sk, sid, g.getLong("frame_counter"),
            g.getString("frame_cmd").hexToBytes(), g.getString("frame_payload").hexToBytes())
        assertEquals(g.getString("frame"), frame.toHexLower())

        val (cmd, payload) = OdCrypto.decryptResponse(sk, g.getString("resp_frame").hexToBytes())
        assertEquals(g.getInt("resp_cmd"), cmd)
        assertEquals(g.getString("resp_payload"), payload.toHexLower())
    }

    @Test fun commandFramesMatchSdk() {
        val g = golden("commands")
        val c = golden("crypto")
        assertEquals(g.getString("read_config"), Od.readConfig().toHexLower())
        assertEquals(g.getString("read_fw"), Od.readFwVersion().toHexLower())
        assertEquals(g.getString("auth1"), Od.authStep1().toHexLower())
        val cn = c.getString("client_nonce").hexToBytes()
        val ch = c.getString("challenge_response").hexToBytes()
        assertEquals(g.getString("auth2"), Od.authStep2(cn, ch).toHexLower())
        assertEquals(g.getString("dw_start"), Od.directWriteStartUncompressed().toHexLower())
        assertEquals(g.getString("dw_data"), Od.directWriteData(byteArrayOf(1, 2, 3, 4)).toHexLower())
        assertEquals(g.getString("dw_end_full"), Od.directWriteEnd(0).toHexLower())
        assertEquals(g.getString("dw_end_fast"), Od.directWriteEnd(1).toHexLower())
    }

    @Test fun encodingsMatchSdk() {
        val g = golden("encoding")
        val grid = g.getJSONArray("grid")
        val h = grid.length(); val w = grid.getString(0).length
        // logical letters → RePaper palette indexes (0=white, 1=black, 2=red, 3=yellow)
        val repaper = mapOf('W' to 0, 'B' to 1, 'R' to 2, 'Y' to 3)
        fun indexes(clampAccent: Boolean, yellowAsAccent: Boolean = false): IntArray {
            val out = IntArray(w * h)
            for (y in 0 until h) for (x in 0 until w) {
                var idx = repaper.getValue(grid.getString(y)[x])
                if (yellowAsAccent && idx == 3) idx = 2       // BWR/BWY panels: Y renders as the accent
                if (clampAccent && idx >= 2) idx = 1          // MONO: any accent renders black
                out[y * w + x] = idx
            }
            return out
        }
        assertEquals(g.getString("mono"), OdEncoding.encode(indexes(clampAccent = true), w, h, ColorScheme.MONO).toHexLower())
        assertEquals(g.getString("bwr"), OdEncoding.encode(indexes(false, yellowAsAccent = true), w, h, ColorScheme.BWR).toHexLower())
        assertEquals(g.getString("bwy"), OdEncoding.encode(indexes(false, yellowAsAccent = true), w, h, ColorScheme.BWY).toHexLower())
        assertEquals(g.getString("bwry"), OdEncoding.encode(indexes(false), w, h, ColorScheme.BWRY).toHexLower())
    }

    @Test fun landingUrlsMatchSdk() {
        val g = golden("landing")
        val withKey = g.getJSONObject("with_key")
        val l = LandingUrl.parse(withKey.getString("url"))
        assertEquals(withKey.getInt("tag_type"), l.tagType)
        assertEquals(withKey.getString("device_id"), l.deviceId)
        assertEquals(withKey.getString("name"), l.name)
        assertEquals(withKey.getString("key"), l.keyHex)
        assertEquals(withKey.getInt("manufacturer"), l.manufacturerId)
        val noKey = g.getJSONObject("no_key")
        val l2 = LandingUrl.parse(noKey.getString("url"))
        assertNull(l2.keyHex)
        assertEquals(noKey.getString("name"), l2.name)
    }

    @Test fun configParseMatchesSdk() {
        val g = golden("config")
        val caps = OdConfig.parse(g.getString("tlv").hexToBytes())
        assertEquals(g.getInt("width"), caps.width)
        assertEquals(g.getInt("height"), caps.height)
        assertEquals(g.getString("scheme"), caps.scheme.name)
        assertEquals(g.getInt("rotation_degrees"), caps.rotation)
        assertEquals(122, caps.viewedWidth)     // 90° mount: viewed size swaps
        assertEquals(250, caps.viewedHeight)
        assertTrue(caps.sessionTimeoutSeconds == 0)
    }
}
